In [3]:
print('hello world!')

hello world!


In [4]:
import numpy as np

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([10,20,30])

In [3]:
print("1d array: ",arr_1d)

1d array:  [10 20 30]


In [4]:
zeros = np.zeros(5)

In [5]:
print("zeros: ",zeros)

zeros:  [0. 0. 0. 0. 0.]


In [10]:
range_arr = np.arange(10)

In [11]:
print("range array: ",range_arr)

range array:  [0 1 2 3 4 5 6 7 8 9]


In [12]:
linear_space = np.linspace(0,1,5)
print("linear space: ",linear_space)

linear space:  [0.   0.25 0.5  0.75 1.  ]


In [16]:
matrix = np.array([[12,23,34],[45,56,67],[78,89,90]])
print(matrix)
print(matrix.shape)

[[12 23 34]
 [45 56 67]
 [78 89 90]]
(3, 3)


In [20]:
flat_arr = np.array([1,2,3,4,5,6])
reshaped_mat = flat_arr.reshape(2,3)
print(reshaped_mat)

[[1 2 3]
 [4 5 6]]


In [24]:
arr1 = np.array([1,2,3,4])
print("multiplied by 2: ",arr1 * 2)
arr2 = np.array([5,6,7,8])
print("element wise add: ",arr1 + arr2)
print("square roots: ",np.sqrt(arr1))

multiplied by 2:  [2 4 6 8]
element wise add:  [ 6  8 10 12]
square roots:  [1.         1.41421356 1.73205081 2.        ]


In [3]:
import numpy as np 
arr3 = np.array([10,20,30,40,50,60,70,80,90,100])
print("first ele: ",arr3[3])
print("first to five eles: ",arr3[0:5])

first ele:  40
first to five eles:  [10 20 30 40 50]


In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame(raw_data)
print(df)

      Name  Age
0    pooja   26
1     vani   43
2     devi   49
3     hari   34
4  praveen   45
5   naveen   23


In [6]:
import pandas as pd


In [9]:
raw_data = {
"Name" : ['pooja','vani','devi','hari','praveen','naveen'],
"Age" : [26 , 43 , 49 , 34 , 45 , 23],
}

In [10]:
df = pd.DataFrame(raw_data)
print(df)

      Name  Age
0    pooja   26
1     vani   43
2     devi   49
3     hari   34
4  praveen   45
5   naveen   23


In [13]:
print(df.head(2))
print(df.info())
print(df.describe())

    Name  Age
0  pooja   26
1   vani   43
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    6 non-null      object
 1   Age     6 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes
None
             Age
count   6.000000
mean   36.666667
std    10.670833
min    23.000000
25%    28.000000
50%    38.500000
75%    44.500000
max    49.000000


In [20]:
ages = df['Age']

In [21]:
print(ages)

0    26
1    43
2    49
3    34
4    45
5    23
Name: Age, dtype: int64
